### ISSUE TITLE
add other genome

### ISSUE THREAD

**Issue by drbecavin** [caleblareau/bap#20]
Hello
Following the reading of your bioRxiv paper, I want to test my scAtacSeq datasets.
But my data are on pig, so I need non referent genome.
I was no able to find in the wiki how to add new genome for bap.

Do you have some tutorial ready for that ?
Thank you

**Comment by caleblareau** [comment]
My apologies-- I've added a new page to the wiki that should help. 

https://github.com/caleblareau/bap/wiki/Reference-Genome

Let me know if any of this is unclear.

**Comment by drbecavin** [comment]
Perfect ! I will try that immediately !

**Comment by caleblareau** [comment]
@drbecavin any luck?

**Comment by drbecavin** [comment]
Nop...
I am running
```
bap2 bam -i /share/data/analysis/000-10x-cellranger-atac/10x_pig/atacseq10x_pig_ko/outs/possorted_bam.bam -o /home/becavin/outs_ko_bap -c 1 -bt CB -bg /home/becavin/Genome/PigBap/chromo.bed --tss-file /home/becavin/Genome/PigBap/tss.bed --mito-chromosome "MT" --blacklist-file /home/becavin/Genome/PigBap/blacklist.bed
```

And it gives
```
Thu Nov 07 17:56:19 CET 2019: Starting bap2 pipeline v0.6.4
Thu Nov 07 17:56:19 CET 2019: Found designated reference genome: hg19
Thu Nov 07 17:56:19 CET 2019: Attempting to parse supplied .bam files for analysis.
Thu Nov 07 17:56:19 CET 2019: Found 21 chromosomes for analysis (including mitochondria).
Thu Nov 07 17:56:19 CET 2019: Splitting input bam files by chromosome for parallel processing.
Thu Nov 07 17:56:19 CET 2019: User specified 1 cores for parallel processing.
Traceback (most recent call last):
  File "/share/apps/local/anaconda3/envs/py37/lib/python3.7/site-packages/bap/bin/python/20_names_split_filt.py", line 93, in <module>
    chrlens[tok[0]] = tok[1].strip()
IndexError: list index out of range
Thu Nov 07 17:56:20 CET 2019: Processing bam file using a Snakemake workflow. This is the most computationally intensive step.
Thu Nov 07 17:56:20 CET 2019: ERROR: Snakemake execution failed. Check /home/becavin/outs_ko_bap/logs/possorted_bam.snakemake.log file for more information. If blank, try allocating more memory.
```

The error is in : Thu Nov 07 17:56:19 CET 2019: Found designated reference genome: hg19
I guess!

In the possorted_bam.snakemake.log file I have
```
FileNotFoundError in line 51 of /share/apps/local/anaconda3/envs/py37/lib/python3.7/site-packages/bap/bin/snake/Snakefile.bap2.chr:
[Errno 2] No such file or directory: '/home/becavin/outs_ko_bap/.internal/samples/possorted_bam.chrbam.txt'
  File "/share/apps/local/anaconda3/envs/py37/lib/python3.7/site-packages/bap/bin/snake/Snakefile.bap2.chr", line 51, in <module>
```

And the posssorted.bam.parameters.txt is
````
bap_version: 0.6.4
script_dir: /share/apps/local/anaconda3/envs/py37/lib/python3.7/site-packages/bap
mode: bam
output: /home/becavin/outs_ko_bap
bamfile: /share/data/analysis/000-10x-cellranger-atac/10x_pig/atacseq10x_pig_ko/outs/possorted_bam.bam
name: possorted_bam
ncores: '1'
cluster: ''
jobs: '0'
peakFile: ''
barcode_prior: none
minimum_barcode_fragments: 0
barcode_whitelist: none
minimum_jaccard_index: 0.0
nc_threshold: 6
regularize_threshold: 4
one_to_one: false
barcoded_tn5: false
keep_read_names: false
proper_pair: 'true'
extract_mito: false
mapq: 30
tssFile: /home/becavin/Genome/PigBap/tss.bed
blacklistFile: /home/becavin/Genome/PigBap/blacklist.bed
bedtoolsGenomeFile: /home/becavin/Genome/PigBap/chromo.bed
mitochr: MT
R: /share/apps/local/anaconda3/envs/py37/bin/R
samtools: /share/apps/local/anaconda3/envs/py37/bin/samtools
bedtools: /share/apps/local/anaconda3/envs/py37/bin/bedtools
bgzip: /share/apps/local/anaconda3/envs/py37/bin/bgzip
tabix: /share/apps/local/anaconda3/envs/py37/bin/tabix
snakemake: /share/apps/local/anaconda3/envs/py37/bin/snakemake
drop_tag: DB
bead_tag: CB
max_insert: 2000
speciesMix: none
```

I am guessing it still try to search for hg19

**Comment by caleblareau** [comment]
The "found reference hg19" I think is just poor logging on my part. Can you post `/home/becavin/Genome/PigBap/chromo.bed`? Is it tab delimited?

**Comment by drbecavin** [comment]
Ok, I have found the bug! 
There was two blank lines at the end of my "chromo.bed" ...
Might be wise to add a test for blank line in your .bed file reader ;)
I'll let you know about the results on pig scATAC-Seq.
Thanks for your help

**Comment by drbecavin** [comment]
P.S.: I have my results on human scATACSeq and I have 3 cells/400 cells with potential multiplets. I am looking at "possorted_bam.jaccardOverlapKnee.png" for that.
Am I right to look at this figure? 
Figure legend for the figures in "knee" folder would help.

**Comment by caleblareau** [comment]
thanks @drbecavin for unearthing the whitespace issue-- pushing a bumped version that will fix this. 

That is the right file, yes; do you mind uploading it here or otherwise emailing it to me to verify? It sounds like if you have only 400 cells that only 3 being multiplets seems likely. I'd also recommend running the 10x solution to see if it corroborates (I don't have much experience running bap on that low of input).

**Comment by drbecavin** [comment]
Here is the file for our human scATAC-Seq dataset: 
![possorted_bam jaccardOverlapKnee](https://user-images.githubusercontent.com/8556087/68764437-ffdfe100-061a-11ea-8db8-4b2dbd5c85c5.png)

It correlates with 10x solution:
```
28.0m 20.42s - Original run had 400 total cell barcodes
28.0m 28.14s - After multiplet exclusions, have 398 total cell barcodes
```

I am processing right now the pig datasets with 10x solution to see if it is the same. I'll get you posted.

**Comment by drbecavin** [comment]
It is done with pig datasets and I do not understand the results:
![possorted_bam jaccardOverlapKnee](https://user-images.githubusercontent.com/8556087/68847978-d339d100-06cf-11ea-978d-72c875c8e1ef.png)
The number of cells passing the knee seems very high.
Whereas the 10x solution was giving:
```
38.0m 26.08s - Original run had 846 total cell barcodes
38.0m 41.53s - After multiplet exclusions, have 845 total cell barcodes
```

**Comment by drbecavin** [comment]
For my other pig dataset I have:
![possorted_bam jaccardOverlapKnee](https://user-images.githubusercontent.com/8556087/68848245-45aab100-06d0-11ea-9791-13b97c982d03.png)

And 10x solution:
```
40.0m 51.6s - Original run had 1,035 total cell barcodes
41.0m 6.57s - After multiplet exclusions, have 1,032 total cell barcodes
```

**Comment by caleblareau** [comment]
yeah so these mostly look pretty concordant, but clearly the second one is potentially off. Can you send me the output from the /final/ folder that is the `barcodeTranslate` file and the `QCstats`? everything that I've benchmarked the 10x solution with bap have agreed until this one.

**Comment by drbecavin** [comment]
[pig_becavin_logs.zip](https://github.com/caleblareau/bap/files/3847567/pig_becavin_logs.zip)
Here are both files.
We will redo the experiment and have more cells in few days, we will see how the numbers grow.

**Comment by caleblareau** [comment]
Apologies; I was hoping to get the source data for this plot since it was the most discordant. 
![68847978-d339d100-06cf-11ea-978d-72c875c8e1ef](https://user-images.githubusercontent.com/16229089/68885732-bb6c4800-06e3-11ea-8714-2829dc3ddc9b.png)

Also, I actually need the `implicatedBarcodes.csv.gz` file as well.

**Comment by drbecavin** [comment]
Yes, this one looks weird.
Here is the file
[possorted_bam.implicatedBarcodes.csv.gz.zip](https://github.com/caleblareau/bap/files/3850994/possorted_bam.implicatedBarcodes.csv.gz.zip)
thanks

**Comment by caleblareau** [comment]
Thanks for sharing! 

So what I wanted to test for was the shared common subsequence (rLCS from the preprint) between the pairs that bap merged. Here's code that does this:

```
library(data.table)
library(dplyr)
library(ggplot2)

# Import data
ib <- fread("possorted_bam.implicatedBarcodes.csv") %>%
  data.frame() %>% filter(merged)

# Compute restricted longest subsequence
rLCS <- function(a,b){
  
  aa <- strsplit(gsub("-1", "", a), "")[[1]]
  bb <- strsplit(gsub("-1", "", b), "")[[1]]
  
  rle_out <- rle(aa == bb)
  value <- max(rle_out$lengths[rle_out$values])
  value <- ifelse(value >0, value, 0)
  return(value)
}
ib$rLCS <- sapply(1:length(ib$barc1), function(i){
  rLCS(as.character(ib$barc1[i]), as.character(ib$barc2[i]))
})

# Sumarize
qplot(ib$rLCS) +
  labs(x = "rLCS for barcode pair", y = "count")
sum(ib$rLCS >= 9)
# Rough expectation
0.001*length(ib$rLCS)

```
And then here's the resulting plot:

<img width="475" alt="Screen Shot 2019-11-15 at 8 16 23 AM" src="https://user-images.githubusercontent.com/16229089/68946283-9548b580-0780-11ea-8bc5-1b717a794020.png">

Basically, since `bap` is finding mostly barcode pairs that share a long common subsequence, I think that a majority of the matched pairs are probably real. However, I noticed that there were ~2,789 barcodes from your input file:

```
length(unique(c(as.character(ib$barc1), as.character(ib$barc2)))
```

which seemed at odds with the ~879 barcodes that were considered by CellRanger. Did you specify the barcode list before running `bap`, or did you let it dynamically determine it?

**Comment by drbecavin** [comment]
No, I ran without mentionning it.
Here is my command line :
````
bap2 bam -i possorted_bam.bam -o outs_ko_bap -c 5 -bt CB -bg PigBap/tss.bed --mito-chromosome "MT" --blacklist-file PigBap/blacklist.bed
```

This 2700 barcodes is really weird !

**Comment by caleblareau** [comment]
Ah okay, so this explains it then. If you dig through the `knee` output folder, there should be another file that shows the fragments / barcode where the ~2700 was determined. This could just be a bad knee call on bap’s part (maybe); how many cells were you expecting to recover? Basically, what happened was that bap by setting a lower threshold found a ton of barcode multiplets that weren’t in the ~800 barcodes that was present in the CellRanger-ATAC output.

**Comment by drbecavin** [comment]
If I look at CellRanger web summary I should get 846 cells. 
I should set manually the threshold then ? But I see no options for that.
I just rerun the script with "--keep-temp-files" to see if any temp file can give more info.

**Comment by caleblareau** [comment]
In the wiki, I show how to use the same barcodes as CellRanger uses-- https://github.com/caleblareau/bap/wiki/10X-scATAC

(see the `-w` flag where you can supply the list of barcodes)

**Comment by caleblareau** [comment]
I'd recommend this for the analysis of 10x data with bap

**Comment by drbecavin** [comment]
Ok, I have run it with -w flag.
Thanks
