### ISSUE TITLE
Significantly different clustering results from bap BAM compared to original

### ISSUE THREAD

**Issue by Austin-s-h** [caleblareau/bap#21]
Hi, I'm not quite sure how to phrase this question/discussion.
I've performed a timecourse of scATAC-Seq and previously have shown that it demonstrates good temporal progression as viewed from UMAP projections. This is maintained through a variety of different modes of analysis.
1. Appending unique identifiers and processing via snapATAC, calling peaks from all cells within a timepoint, and then merging these peak calls together. Processing and visualization using Monocle3.
2. Above except calling peaks based on clusters within each timepoint.
3. The same cells as 1&2, creating a peak matrix from 10X called peaks. 

Despite these three different peaksets, (190k, 290k, and 373k peaks), the clustering looks pretty identical.

However, when I process all of my samples using bap and merge the resulting bam files, I obtain much less separation between known timepoints. I have inspected the knee plots for bap and it seems fine, and I merge an average of ~10% of my 10X called cells in line with expectations. Even by creating matricies between bap-cells and the identical peaksets, there is a loss of separation. Calling peaks from the new bap cells also looks identical to the previous peaksets. Could this be an artifact of bap? Would how it modifies the aligned reads lead to loss of cell information?

Digging deeper, I tried to identify if there were any clear clusters of bap-merged cells within my non-bap corrected data. There were not. Could you provide insight into why processing via bap is resulting in loss of biological signal?

Non-Bap processed data, 10X called peaks
![10x_Peaks](https://user-images.githubusercontent.com/44502805/68446894-0fd76b00-01ac-11ea-8e41-53e34a717ccb.png)

Bap processed data, 10X called peaks
![bap_data](https://user-images.githubusercontent.com/44502805/68447763-13b8bc80-01af-11ea-82ea-80154d08fb87.png)

**Comment by caleblareau** [comment]
yikes; this is obviously a hugely complex end point with a lot of moving pieces, so it's hard to imagine what exactly went wrong (though I appreciate the effort in trying to control for things like peak sets). 

Just so I'm clear on a few points:
- The time points are 5 different 10x channels I'm guessing? And you ran bap separately on each of them?
- Are you using the fragments files from CellRanger-ATAC from bap to make your counts matrices? 
- You are using bap2 for all processing? 

Since it sounds like you have bap and non-bap'd data in the same peak sets, can you post a plot of the counts per million of the rowSums of the counts matrix (to see if there is some dramatic shift in fragments overlapping peaks)?

**Comment by Austin-s-h** [comment]
1. Yes, these were 5 different 10x scATAC libraries, corresponding to 5 different stages of cell differentiation, there are known, meaningful differences across these timepoints. I ran bap on the output of each timepoint/library individually.
2. I am comparing merged BAM files exported right from cellranger-atac to merged BAM files from bap. The count matrices were generated using a 10x peakset generated by cellranger-atac aggr. 
3. Yes, this is all using bap2 version 0.6.4

In checking the rowSums, I noticed that the 10x data is not binarized, this may make a significant difference. However, I do have a version (peaks by cluster) that is binarized for both the bap and non-bap processed data. I'll look into that. The first graph is the 10x, the second is bap processed. The median of the rowSum is plotted, there are some outliers.

![non_bap_density](https://user-images.githubusercontent.com/44502805/68449561-9ba1c500-01b5-11ea-8c01-199f6ed4a862.png)
![bap_density](https://user-images.githubusercontent.com/44502805/68449554-980e3e00-01b5-11ea-9c2f-6c219fbe241f.png)

**Comment by Austin-s-h** [comment]
So, binarizing the matrix from my first example, things change for sure, but the pattern is still much more consistent than the bap processed data.
![binarized_non-bap](https://user-images.githubusercontent.com/44502805/68450061-9a719780-01b7-11ea-8619-eb1560428cde.png)

**Comment by caleblareau** [comment]
Thanks for sending these... very interesting.

1) The plot that I actually had in mind was a scatter plot; bap'd data on one axis; non-bap'd data on the other axis; each dot is a point (maybe log scaled). This would directly indicate if there is some gross peak alterations
2) I haven't explicitly tried anything sophisticated with 10x data with bap (it's mostly been PBMCs as a function of what I can get a hold of). Though it'd be surprising and disappointing if merging fragments from the multiplets somehow dilutes signal in a biological system like this, I don't necessarily have evidence in the 10x platform that the signal gets better. Along these lines...
3) 10x is distributing a script to filter out barcode multiplets by identifying the barcode wth the most fragments per multiplet and then filtering out the other ones. Then, you can use `aggr` on a filtered barcode set, which may give you something desirable (the 10x non-binary counts and the removed barcode multiplets)

Might I ask how you're going from bap output -> reads in peaks?

**Comment by Austin-s-h** [comment]
I can work on generating the plot you mention, it would be interesting to see if there is a shift at higher/lower sampled regions.
An even heavier-handed approach would be to remove all cells that bap called as multiplets. Based upon the seemingly random distribution through my data, I would expect that this wouldn't affect the overall structure. I can test this as well. 
Aligned reads from bap (per library) were modified to contain a library-specific tag along with the bap barcode in the read name. These were then namesorted for input into snaptools. 
I used snaptools to make snap objects on this bamfile, and then added the peak matrix to the snapfile. This is nice because I can create multiple copies and with different peak matrices. So, I guess you could say I'm using snaptools to generate the cell (grouped reads from the bam file) by peak (simple bedfile of locations) matrix.

**Comment by Austin-s-h** [comment]
The only way I could see bap muddling the signal is that if it is merging two (or in some cases many) cells together that are actually not the same. I don't know the details of how it determines this, but from what I understood it is essentially pcr duplicates of individual loci being associated with two barcodes at a high enough frequency to pass a threshold. I may have enough information in my dataset to indicate the distance between merged cells in my UMAP space. If this is the case, it could indicate if there is abberent merging of cells that really shouldn't be merged. It also could help identify if there is a subset of cells that are close in 3d space and should be merged and those that should not.

**Comment by caleblareau** [comment]
Hi @Austin-s-h, I was thinking more about this -- we should have a very low false positive rate for merges, so I don't anticipate that muddying the signal. Moreover, merges are occurring within your timepoint, so it doesn't explain the embedding plots that you are showing. Just to eliminate one other variable, have you run the output of CellRangerATAC through SnapTools and verified that the way that SnapTools is creating the peaks x cells matrix isn't at fault here? (seems unlikely but also seems to be the other variable feature of the workflows).

**Comment by Austin-s-h** [comment]
The embedding plot I've shown is just a simple label of if that cell was merged during BAP analysis using the barcode translation output. It isn't showing groups of cells that were merged together. I'll have some more time on Monday to re-run things.
