### ISSUE TITLE
Regenerate the fragment for the human/mouse cell line in the Nature Biotechnology paper

### ISSUE THREAD

**Issue by Puriney** [caleblareau/bap#25]
Hello,

I have an interest in the human/mouse mix data (https://www.ncbi.nlm.nih.gov/sra?term=SRX5124174) in your Nature Biotechnology paper. The fragment.tsv file is not available at GEO unlike other samples in the same paper.

I was wondering if you could share the fragment.tsv file like you did for other samples for example the mouse. Or could you show me how to process the fastq to create the fragment.tsv file.

It has 4 pairs of reads:
```
SRR8310510_1.fastq.gz  SRR8310511_2.fastq.gz  SRR8310513_1.fastq.gz
SRR8310510_2.fastq.gz  SRR8310512_1.fastq.gz  SRR8310513_2.fastq.gz
SRR8310511_1.fastq.gz  SRR8310512_2.fastq.gz
```

I am not clear about how to chain up the steps. For example, I have questions in below:

1. Should I use v2.1-multi to `bap-barcode`?
2. How to run `bap-reanno`? What is this command doing? Do I just simply `bap-reanno <in_bam> <out_bam>`?
3. Since the run has 4 pairs of reads, does the `bap bam -i` support multiple bam files in the same time? If not, does it mean I will process them one-by-one to generate the fragment.tsv and finally merge all these fragment.tsv files?

Many thanks.

**Comment by caleblareau** [comment]
Hi, I presently don't have the fragments file, but I'm happy to help generate it on my side if this proves challenging.

1) Yes, this experiment is the dsci-ATAC species mix (which is what I asume that you want). 
2) The `bap-reanno` step simply modifies the bam such that the cell barcode is moved from the sequence header to a sam tag. Yes, the format is as you've described. 
3) I would recommend using `bap2`, with all of the other command line parameters (just drop it in for `bap`, which automatically generates the fragments file.  Since these fastqs all came from the same experiment, I would recommend merging them (`samtools merge`) into 1 bam and then running `bap2`

I hope this helps!

**Comment by Puriney** [comment]
Hello Caleb,
As you can see in this issue (https://github.com/caleblareau/bap/issues/24), I cannot make it working on my side so far. I really need your help to generate the fragment files of the human/mouse mix (https://www.ncbi.nlm.nih.gov/sra?term=SRX5124174).

I noticed the `bap2 support` has two versions of mix species. hg19-mm10_nochr and hg19-mm10. Does the "hg19-mm10_nochr" mean there is no chr prefix, like 1, 2, X, Y, instead of chr1, chr2? If so, could you use this reference to run like in your paper? Just clarify, we are interested in the cell line and we are not technically asking the exact fragment file produced in the paper.

My email is yyan7@mdanderson.org

Thank you for your help.

**Comment by Puriney** [comment]
Files were kindly re-generated and provided by the author.

**Comment by caleblareau** [comment]
@Puriney I've pushed v0.6.7 that I think solves this issue now. Let me know if you still have interest in running the tool yourself, and if so, if it works now for you.

**Comment by Puriney** [comment]
Hello Caleb,
Thank you very much. I upgraded and now `bap` works. 

Yes, we probably will look into other data, in particular, the 16k cells loading. I found this dataset seems to have on average 1k-2k fragments per cell from the eyeball. I was curious if the 16k cell loading could have higher fragments per cell.

![barnyard_category_done](https://user-images.githubusercontent.com/1233372/82971493-6bc2df00-9f98-11ea-9496-4f938f3094d3.png)

I want to get the logics about running `bap` having grabbed all the pieces in the wiki. Say I start from the two pairs of fastq.gz reads that are downloaded from your paper.

```
## Barcode
bap-barcode v2.1-multi -a fileA.R1.fastq.gz -b fileA.R2.fastq.gz --nmismatches 1 -o fileA
bap-barcode v2.1-multi -a fileB.R1.fastq.gz -b fileB.R2.fastq.gz --nmismatches 1 -o fileB

## Align
bwa mem /path/to/hg19.fa fileA_c001_1.fastq.gz fileA_c001_2.fastq.gz | samtools view -bS - |  samtools sort -@ 4 - -o fileA.bam
bwa mem /path/to/hg19.fa fileB_c001_1.fastq.gz fileB_c001_2.fastq.gz | samtools view -bS - |  samtools sort -@ 4 - -o fileB.bam

## Merge bams in this case
samtools merge project.bam fileA.bam fileB.bam
samtools sort -@ 4 project.bam -o project.sorted.bam
samtools index project.sorted.bam

## Reanno
bap-reanno project.sorted.bam project.sorted.reanno.bam

## Regenerate fragments
bap2 bam -i project.sorted.reanno.bam -o project_result  -r hg19
```

My question is, in the `bap2 bam` step, do I need to specify a cell barcode tag?

---
There is one more question that is probably out of the scope of `bap`. Appreciate it if you can answer.

How do you call peaks from the fragments? I tracked your paper and I did not get a clear answer. The SnapATAC and ArchR tool seem to firstly cluster cells based on a 50k-width bin by cell matrix, run MACS2 on each subcluster iteratively, and finally, merge those peaks. I know there is no golden method, but I am curious what is the method used in your paper. Could you show me some code snippets as some concrete examples? Many thanks.

**Comment by caleblareau** [comment]
Hi Yun,

I’m not sure off the top of my head, but I think that these were all relatively shallow sequence as they were control experiments.
