### ISSUE TITLE
bap-barcode extremely low success rate

### ISSUE THREAD

**Issue by mailcolm9** [caleblareau/bap#27]
Hi,

I follow the instruction in wiki on how to debarcode the files, and debarcode the Nature Biotech paper, and the success rate is very low, all below 5% which make the processed file very small. Could you take a look on this issue?

`cat *.log

Parsing read pairs:
SRR8994135_1.fastq.gz
SRR8994135_2.fastq.gz

735648 reads parsed with barcodes (1.96% success)
Total reads that failed: 36787203

Of reads that could not be parsed that had valid, detectable constants:
1774 had a bad BC1 barcode sequence
40 had a bad BC2 barcode sequence
122 had a bad BC3 barcode sequence
82 had a bad Tn5 barcode sequence`

`-rwxrwxrwx 1 zonghao zonghao  243 Jun  7 14:34 ConvertName.sh
-rw-rw-r-- 1 zonghao zonghao 4.0M Jun  8 12:46 debarcode-c001_1.fastq.gz
-rw-rw-r-- 1 zonghao zonghao 3.3M Jun  8 12:46 debarcode-c001_2.fastq.gz
-rw-rw-r-- 1 zonghao zonghao 4.0M Jun  8 13:06 debarcode-c002_1.fastq.gz
-rw-rw-r-- 1 zonghao zonghao 3.3M Jun  8 13:06 debarcode-c002_2.fastq.gz
-rw-rw-r-- 1 zonghao zonghao 4.0M Jun  8 13:26 debarcode-c003_1.fastq.gz
-rw-rw-r-- 1 zonghao zonghao 3.3M Jun  8 13:26 debarcode-c003_2.fastq.gz
-rw-rw-r-- 1 zonghao zonghao 4.0M Jun  8 13:47 debarcode-c004_1.fastq.gz
-rw-rw-r-- 1 zonghao zonghao 3.3M Jun  8 13:47 debarcode-c004_2.fastq.gz
-rw-rw-r-- 1 zonghao zonghao 4.0M Jun  8 14:07 debarcode-c005_1.fastq.gz
-rw-rw-r-- 1 zonghao zonghao 3.2M Jun  8 14:07 debarcode-c005_2.fastq.gz
-rw-rw-r-- 1 zonghao zonghao 4.0M Jun  8 14:28 debarcode-c006_1.fastq.gz
-rw-rw-r-- 1 zonghao zonghao 3.3M Jun  8 14:28 debarcode-c006_2.fastq.gz
-rw-rw-r-- 1 zonghao zonghao 4.0M Jun  8 14:48 debarcode-c007_1.fastq.gz
-rw-rw-r-- 1 zonghao zonghao 3.3M Jun  8 14:48 debarcode-c007_2.fastq.gz
-rw-rw-r-- 1 zonghao zonghao 138K Jun  8 07:42 debarcode-c008_1.fastq.gz
-rw-rw-r-- 1 zonghao zonghao 119K Jun  8 07:42 debarcode-c008_2.fastq.gz
-rw-rw-r-- 1 zonghao zonghao  363 Jun  8 12:27 debarcode-debarcode.sumstats.log
-rw-rw-r-- 1 zonghao zonghao    0 Jun  8 12:27 debarcode.stderr.txt
-rw------- 1 zonghao zonghao  14K Jun  8 12:27 nohup.out
-rw-rw-r-- 1 zonghao zonghao  345 Jun  8 00:50 RunBAPBarcode.sh
drwxrwxr-x 2 zonghao zonghao 4.0K Jun  8 01:24 SRR8994127
-rw-rw-r-- 1 zonghao zonghao 555M Jun  7 17:34 SRR8994127_1.fastq.gz
-rw-rw-r-- 1 zonghao zonghao 251M Jun  7 17:34 SRR8994127_2.fastq.gz
drwxrwxr-x 2 zonghao zonghao 4.0K Jun  8 01:56 SRR8994128
-rw-rw-r-- 1 zonghao zonghao 542M Jun  7 17:33 SRR8994128_1.fastq.gz
-rw-rw-r-- 1 zonghao zonghao 245M Jun  7 17:33 SRR8994128_2.fastq.gz
drwxrwxr-x 2 zonghao zonghao 4.0K Jun  8 02:29 SRR8994129
-rw-rw-r-- 1 zonghao zonghao 555M Jun  7 17:34 SRR8994129_1.fastq.gz
-rw-rw-r-- 1 zonghao zonghao 252M Jun  7 17:34 SRR8994129_2.fastq.gz
drwxrwxr-x 2 zonghao zonghao 4.0K Jun  8 03:01 SRR8994130
-rw-rw-r-- 1 zonghao zonghao 558M Jun  7 17:34 SRR8994130_1.fastq.gz
-rw-rw-r-- 1 zonghao zonghao 253M Jun  7 17:34 SRR8994130_2.fastq.gz
drwxrwxr-x 2 zonghao zonghao 4.0K Jun  8 05:22 SRR8994131
-rw-rw-r-- 1 zonghao zonghao 2.3G Jun  7 17:55 SRR8994131_1.fastq.gz
-rw-rw-r-- 1 zonghao zonghao 1.1G Jun  7 17:55 SRR8994131_2.fastq.gz
drwxrwxr-x 2 zonghao zonghao 4.0K Jun  8 07:42 SRR8994132
-rw-rw-r-- 1 zonghao zonghao 2.3G Jun  7 17:55 SRR8994132_1.fastq.gz
-rw-rw-r-- 1 zonghao zonghao 1.1G Jun  7 17:55 SRR8994132_2.fastq.gz
drwxrwxr-x 2 zonghao zonghao 4.0K Jun  8 10:02 SRR8994133
-rw-rw-r-- 1 zonghao zonghao 2.3G Jun  7 17:55 SRR8994133_1.fastq.gz
-rw-rw-r-- 1 zonghao zonghao 1.1G Jun  7 17:55 SRR8994133_2.fastq.gz
drwxrwxr-x 2 zonghao zonghao 4.0K Jun  8 12:27 SRR8994134
-rw-rw-r-- 1 zonghao zonghao 2.3G Jun  7 17:55 SRR8994134_1.fastq.gz
-rw-rw-r-- 1 zonghao zonghao 1.1G Jun  7 17:55 SRR8994134_2.fastq.gz`

**Comment by caleblareau** [comment]
I think that the dataset download is NOT the combinatorial Tn5 library, so in your invocation, specify the correct demultiplexing mode (v2.1 I think)

**Comment by mailcolm9** [comment]
I will try it and let you know, many thanks!

**Comment by mailcolm9** [comment]
OK, it turns out I should use v2.1. Thank you!
