### ISSUE TITLE
GRCh38/mm10 species mixing genome --mito-chromosome

### ISSUE THREAD

**Issue by fderop** [caleblareau/bap#29]
Hello,

I am trying to run bap2 on a species mixing dataset. I have successfully loaded the custom genome. How can I specify both the human and mouse mitochondrial (GRCh38_chrM and mm10_chrM) chromosome names in the --mito-chromosome option? I am using the GRCh38/mm10 hybrid genome by 10x (https://support.10xgenomics.com/single-cell-gene-expression/software/release-notes/build#GRCh38mm10_3.1.0).

Kind regards,

Florian

**Comment by caleblareau** [comment]
Thanks for the comment. To be totally honest, I didn’t build out the mitochondrial option that well in the context of species mixing. Currently, it just processes the human chromosome for the built in reference genomes. Is there specific functionality that you would want for mitochondria associated with the mix?

**Comment by fderop** [comment]
Hello Caleb,

Thank you for your response. It would be convenient if the `--extract-mito` functionality would work for species mixed data, but since that is something I can achieve with SAMtools and a for-loop as well, it's fine if BAP2 does not offer this functionality out of the box. However, I am now facing new problems: the data that I want to test is MiSeq micro, for a total of 2M reads. I think the coverage of some chromosomes is giving troubles for the workflow, but I don't know enough about the tool to pinpoint what exactly goes wrong. Here is my log file and command:

[S1_exp.parameters.txt](https://github.com/caleblareau/bap/files/4865951/S1_exp.parameters.txt)
[S1_exp.snakemake.log](https://github.com/caleblareau/bap/files/4865949/S1_exp.snakemake.log)

``module load SAMtools
module load tabix

bap2 bam \
--input bams_unsplit/S1_exp.bam \
--output bap2_output \
--ncores 1 \
--bedtools-genome /ddn1/vol1/staging/leuven/stg_00002/lcb/fderop/data/00000000_res/GRCh38_mm10/refdata-cellranger-atac-GRCh38-and-mm10-1.2.0/fasta/genome.fa.fai \
--blacklist-file /ddn1/vol1/staging/leuven/stg_00002/lcb/fderop/data/00000000_res/GRCh38_mm10/refdata-cellranger-atac-GRCh38-and-mm10-1.2.0/regions/blacklist.bed \
--tss-file /ddn1/vol1/staging/leuven/stg_00002/lcb/fderop/data/00000000_res/GRCh38_mm10/refdata-cellranger-atac-GRCh38-and-mm10-1.2.0/regions/tss.bed \
--mito-chromosome GRCh38_chrM \
--barcode-whitelist /ddn1/vol1/staging/leuven/stg_00002/lcb/fderop/data/00000000_barcodes/20200227_HyDrop-ATAC_96x96x96/full_barcodes.txt \
--bead-tag CB
```

When I run the command with a genome.fa.fai file that omits all small contigs, I still get the same error:

[S1_exp_nocontigs.snakemake.log](https://github.com/caleblareau/bap/files/4865968/S1_exp_nocontigs.snakemake.log)
[S1_exp_nocontigs.parameters.txt](https://github.com/caleblareau/bap/files/4865969/S1_exp_nocontigs.parameters.txt)

Do you know if this can be solved other than by manually omitting the offending chromosomes from the genome file?

Kind regards,

Florian

**Comment by fderop** [comment]
I think we have found the problem. BAP2 assumes paired end data to generate `.frag.bedpe.gz` files. Our data is single end.

**Comment by caleblareau** [comment]
Hi Florian,

Yes, the single-end nature of the data is definitely a big violation of what’s assumed in bap (utilizing both Tn5 insertions to map doublets). Is the goal mostly to preprocess this ATAC-seq data? It sounds like you’ve looked through the code a bit, so maybe the best solution would be to create your own custom pipeline and reuse whatever code here is potentially useful?

**Comment by fderop** [comment]
Hi Caleb,

Thanks for your time. We have engineered a custom protocol, but only sequenced single end. We are also trying to investigate possible barcoding contamination or similar issues. I think we might have to find other tools that can check for PCR duplicates.

Kind regards,

Florian
