### ISSUE TITLE
Error in generating `*frag.bedpe.annotated.tsv` file

### ISSUE THREAD

**Issue by anamariaelek** [caleblareau/bap#31]
I encountered two related issues when trying to run the pipeline on my bam files mapped to a custom genome.

Initially, the pipeline was failing to generate `*frag.bedpe.annotated.tsv` files for chromosomes that have no reads mapped to them, becaue the empty `*frag.bedpe.gz` input files were generating error in the downstream R script.
[cell_barcodes.MAPQ30.CB.snakemake.log](https://github.com/caleblareau/bap/files/5598671/cell_barcodes.MAPQ30.CB.snakemake.log)
After trying to work around this by removing these chromomes from the genome file, the same job still fails, but this time failing to generate the `*frag.bedpe.annotated.tsv`  for the last file being analyzed, even though the relevan imputs are generated and are not empty. I am quite sure this is not the problem of a particular scaffold or a set of files for it, because when I remove the failing scaffold, I get the same error for the scaffold that is now the last one being processed. 

Here is the relevant bit of the log file, and below I attach the whole file as well:
```
Error in merge.data.table(frags, bead_read, by = "read_name") :
  Elements listed in `by` must be valid column names in x and y
Calls: %>% -> na.omit -> merge -> merge -> merge.data.table
Execution halted
gzip: /users/asebe/aelek/proj/scATAC_nvec_Oct20/scATAC_pro/output_50m_PFA/bap2_out/temp/filt_split/cell_barcodes.MAPQ30.CB.scaffold_811.frag.bedpe.
annotated.tsv: No such file or directory
```

The only idea that I could think of is that this is maybe a latency issue as suggested in the bap log output, and if so, is there a way to run the snakemake pipeline within bap with increased value of `--latency-wait` parameter?

Thank you in advance,
Anamaria

**Comment by caleblareau** [comment]
Hmm interesting... Thanks for the detailed error message. I'd agree that increasing the `--latency-wait` is a reasonable idea for a next step.  

To edit the code, I'd recommend to 1) clone the repository; 2) modify the source code/snakemake call (which can be found here: https://github.com/caleblareau/bap/blob/master/bap/cli_bap2.py#L221); 3) install a develop version so that you can tweak things in the fly (https://stackoverflow.com/questions/19048732/python-setup-py-develop-vs-install).

**Comment by anamariaelek** [comment]
Eventually, this was not an issue, but rather the empty beads tsv files; I I worked around it by modifying the R scripts where necessary (https://github.com/anamariaelek/bap/commit/b0cb0304f340f099d646bffa84a95739810bc6fe).
