### ISSUE TITLE
Write raw barcode and corrected barcode in FASTQ name comment section so bwa -C can write the BAM tags directly

### ISSUE THREAD

**Issue by ghuls** [caleblareau/bap#32]
Write raw barcode and corrected barcode in FASTQ name comment section when using `bap-barcode`
https://github.com/caleblareau/bap/wiki/Working-with-BioRad-data

bwa supports the `-C` option:

> -C | Append append FASTA/Q comment to SAM output. This option can be used to transfer read meta information (e.g. barcode) to the SAM output. Note that the FASTA/Q comment (the string after a space in the header line) must conform the SAM spec (e.g. BC:Z:CGTAC). Malformated comments lead to incorrect SAM output.

https://github.com/lh3/bwa/issues/317#issuecomment-785155711

This avoid the need to run `bap-reanno` afterwards on the BAM, as the tags will be added already by BWA.

```
# bwa mem: Add -C and -t.
# samtools view: Write uncompressed BAM when converting SAM output to BAM (makes no sense to compress, when sorting it in the next step)
# samtools sort: Put input BAM (-) argument last.
bwa mem -C -t 8 /path/to/hg19.fa debarcode-c001_1.fastq.gz debarcode-c001_2.fastq.gz \
    | samtools view -b -u - \
    | samtools sort -@ 4 -o debarcode.bam -

samtools index debarcode.bam
```

**Comment by caleblareau** [comment]
Oh wow, this is great to know. Thanks for pointing this out!

On Feb 24, 2021, at 2:30 PM, Gert Hulselmans <notifications@github.com<mailto:notifications@github.com>> wrote:



Write raw barcode and corrected barcode in FASTQ name comment section when using bap-barcode
https://github.com/caleblareau/bap/wiki/Working-with-BioRad-data

bwa supports the -C option:

-C | Append append FASTA/Q comment to SAM output. This option can be used to transfer read meta information (e.g. barcode) to the SAM output. Note that the FASTA/Q comment (the string after a space in the header line) must conform the SAM spec (e.g. BC:Z:CGTAC). Malformated comments lead to incorrect SAM output.

lh3/bwa#317 (comment)<https://github.com/lh3/bwa/issues/317#issuecomment-785155711>

This avoid the need to run bap-reanno afterwards on the BAM, as the tags will be added already by BWA.

**Comment by ghuls** [comment]
My `/barcode_10x_scatac_fastqs.sh `script can generate this kind of FASTQ files (and can do it fast) (requires R1, R2 (barcode) and R3). The barcode extraction and correction script for BioRad v2.1 is not in the repo yet, but will be soon. https://github.com/aertslab/single_cell_toolkit

**Comment by ghuls** [comment]
My own version processed a BioRad v2 barcode FASTQ file (extracting and correcting) in 6minutes 45 seconds (4G gzipped FASTQ, 61 million reads).

It writes a `br:Z:FoundNoAdapters` SAM field if the adapters could not be found (2 mismatches allowed per barcode).
If the adapters are found it tries to correct them (only 1 mismatch allowed per subbarcode of 7 bp) and a `CB:Z:barcode` tag will be written, which will be added as a SAM tag by `bwa -C`.

`br:Z:0,0,0` ==> each subbarcode found with zero mismatches
`br:Z:0,0,-1` ==> subbarcode 1 and 2 found with zero mismatches, subbarcode 3 has more than 1 mismatch
`br:Z:1,0,0` ==> subbarcode 1 has 1 mismatch, subbarcode 2 and 3 have zero mismatches

```
@NB551608:167:HNYFJBGXC:1:11101:23308:1045 CB:Z:TCGGATGCATCAGTAGATAGG   br:Z:0,0,0
TCGGATGCATCAGTAGATAGG
+
AAAAAEEEEEEEEEEEEEEEE
@NB551608:167:HNYFJBGXC:1:11101:12776:1046 CB:Z:AAGTTATAGTTTCTGATAGAC   br:Z:0,0,0
AAGTTATAGTTTCTGATAGAC
+
AAAAAEEEEEEEEEEEEEEEE
@NB551608:167:HNYFJBGXC:1:11101:22610:1046 br:Z:0,0,-1
GATCACCAGGCATGGTACAAT
+
A6AAAEA/EEEE/A//EE/E/
@NB551608:167:HNYFJBGXC:1:11101:13107:1047 br:Z:FoundNoAdapters
NNNNNNNNNNNNNNNNNNNNN
+
AAAAAAAAAAAAAAAAAAAAA
@NB551608:167:HNYFJBGXC:1:11101:10805:1047 CB:Z:GTTAGGACGGCTGCGGTTCAC   br:Z:0,0,0
GTTAGGACGGCTGCGGTTCAC
+
AAAAAEEEEEEEEEEEEEEEE
@NB551608:167:HNYFJBGXC:1:11101:14242:1035 CB:Z:GATCACCAACGGTGGGAGCCT   br:Z:1,0,0
GATCANCAACGGTGGGAGCCT
+
AAAAA#EEEEEEE6EEAEEEE
```

**Comment by caleblareau** [comment]
This looks great! My only comment is that because these are the bead barcodes and haven't yet been collapsed, CB would probably not be the sam tag that I'd recommend using for ease of interpretation, but this is fairly nit picky. 

Overall, this looks great-- did you want anything from me? Can I link you repo from the bap repo?

**Comment by ghuls** [comment]
Which tag would you recommend?

Next week the code will normally be in the github repo (code needs some cleanup and some documentation). After that it can be linked on the bap repo.

**Comment by caleblareau** [comment]
by my convention, I use XB for the parsed barcode in the read and then DB after the bead merging (https://github.com/caleblareau/bap/wiki/FAQ) to avoid confusion with the slightly different meaning from CB (note that DB and CB would be intuitively the same thing)

**Comment by ghuls** [comment]
@caleblareau 

Setting a `score_cutoff` in with `process.extractOne` might be slightly faster as you don't need to generate the full list to get the max score. (untested code)

https://github.com/caleblareau/bap/blob/467e1939a820dd555aa0901f511bcde5f8af8428/bap/barcode/modes/barcodeHelp.py#L51-L63

```python
def prove_barcode(bc, valid_set, n_mismatch):
	'''
	Function that takes a putative barcode and returns the nearest valid one
	'''
		
	if(bc in valid_set):
		return(bc, "0")
	else:
		eo = process.extractOne(bc, valid_set, score_cutoff=(len(bc)-n_mismatch)/len(bc)*100))
		if eo: 
			return(eo[0], "1")
		else:
			return("N"*len(bc), "0")
```
https://github.com/seatgeek/fuzzywuzzy/blob/master/fuzzywuzzy/process.py#L197-L222

**Comment by ghuls** [comment]
Scripts are available for a while.

  https://github.com/aertslab/single_cell_toolkit/blob/master/extract_and_correct_biorad_barcode_in_fastq.sh

The script that does the actual BioRad barcode extraction and correction:
  `https://github.com/aertslab/single_cell_toolkit/blob/master/extract_and_correct_biorad_barcode_in_fastq.seq`

**Comment by caleblareau** [comment]
Thanks! I've updated the wiki (https://github.com/caleblareau/bap/wiki/Working-with-BioRad-data) to reflect this nice tool. I'm planning on leaving the documentation and functionality for the sake of potentially reproducing our prior work but I've now prominently displayed this tool. Thanks for working with the data!
