### ISSUE TITLE
ValueError: invalid contig `chrM`

### ISSUE THREAD

**Issue by ShijingZHANG** [caleblareau/bap#33]
Hello! Thank you for the great tool :)
I have a question and I will be grateful if you can help me~

When I run "bap2 bam -i alignment.last.bam -o bap_out -r hg19", I got the following error message.
"""
Traceback (most recent call last):
  File "/Users/zhangshijing/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/zhangshijing/anaconda3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/zhangshijing/Documents/scATAC-Seq/bap/bap/bin/python/20_names_split_filt.py", line 71, in writeBeadReadName
    Itr = bam.fetch(str(chrom),multiple_iterators=True)
  File "pysam/libcalignmentfile.pyx", line 1082, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 685, in pysam.libchtslib.HTSFile.parse_region
ValueError: invalid contig `chrM`
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/zhangshijing/Documents/scATAC-Seq/bap/bap/bin/python/20_names_split_filt.py", line 102, in <module>
    toy_out = pool.map(writeBeadReadName, zip(chrs, read_barcode_file))
  File "/Users/zhangshijing/anaconda3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/zhangshijing/anaconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ValueError: invalid contig `chrM`
Thu Mar 04 22:26:13 HKT 2021: Processing bam file using a Snakemake workflow. This is the most computationally intensive step.
Thu Mar 04 22:26:14 HKT 2021: ERROR: Snakemake execution failed. Check bap_out/logs/alignment.last.snakemake.log file for more information. If blank, try allocating more memory.

Before running bap2, I use GATK to remove the "chrM" reads in my bam file. After I see this error, I use "samtools view -h alignment.last.bam | grep -c "chrM"" to check whether there is "chrM" existing in my bam file, and the result shows that there is no "chrM" reads in my bam file.

I have attached the snakemake.log file and the head&tail 100 lines of the alignment.last.bam file. 
[alignment.last.snakemake.log](https://github.com/caleblareau/bap/files/6084408/alignment.last.snakemake.log)
[alignment_bam_head100.txt](https://github.com/caleblareau/bap/files/6084428/alignment_bam_head100.txt)
[alignment_bam_tail100.txt](https://github.com/caleblareau/bap/files/6084452/alignment_bam_tail100.txt)

Thank you!

Best Wishes,
Shijing

**Comment by ShijingZHANG** [comment]
The commands I use to process the bwa alignment .bam file.  (alignments.possorted.tagged.bam)
> gatk MarkDuplicates -I alignments.possorted.tagged.bam -O alignment.picard.rmdup.bam --REMOVE_SEQUENCING_DUPLICATES true -M tagged.log
> samtools view -h -f 2 -q 30 alignment.picard.rmdup.bam|grep -v chrM|samtools sort -O bam -@ 5 -o - > alignment.last.bam

**Comment by caleblareau** [comment]
Thanks for the detailed error reporting and using the tool! Can you send the output of

samtools idxstats alignment.last.bam

**Comment by ShijingZHANG** [comment]
Thank you for the quick reply.
The output of `samtools indstats alignment.last.bam` is as following:

chr1	249250621	1459	0
chr2	243199373	1216	0
chr3	198022430	993	0
chr4	191154276	661	0
chr5	180915260	858	0
chr6	171115067	770	0
chr7	159138663	769	0
chr8	146364022	618	0
chr9	141213431	651	0
chr10	135534747	745	0
chr11	135006516	799	0
chr12	133851895	759	0
chr13	115169878	416	0
chr14	107349540	502	0
chr15	102531392	486	0
chr16	90354753	607	0
chr17	81195210	742	0
chr18	78077248	340	0
chr19	59128983	695	0
chr20	63025520	364	0
chr21	48129895	156	0
chr22	51304566	318	0
chrX	155270560	315	0
chrY	59373566	16	0
chr1_gl000191_random	106433	0	0
chr1_gl000192_random	547496	0	0
chr4_gl000193_random	189789	0	0
chr4_gl000194_random	191469	0	0
chr7_gl000195_random	182896	8	0
chr8_gl000196_random	38914	0	0
chr8_gl000197_random	37175	0	0
chr9_gl000198_random	90085	2	0
chr9_gl000199_random	169874	0	0
chr9_gl000200_random	187035	0	0
chr9_gl000201_random	36148	0	0
chr11_gl000202_random	40103	0	0
chr17_gl000203_random	37498	0	0
chr17_gl000204_random	81310	0	0
chr17_gl000205_random	174588	4	0
chr17_gl000206_random	41001	0	0
chr18_gl000207_random	4262	0	0
chr19_gl000208_random	92689	0	0
chr19_gl000209_random	159169	0	0
chr21_gl000210_random	27682	0	0
chrUn_gl000211	166566	0	0
chrUn_gl000212	186858	2	0
chrUn_gl000213	164239	0	0
chrUn_gl000214	137718	0	0
chrUn_gl000215	172545	0	0
chrUn_gl000216	172294	0	0
chrUn_gl000217	172149	0	0
chrUn_gl000218	161147	0	0
chrUn_gl000219	179198	0	0
chrUn_gl000220	161802	60	0
chrUn_gl000221	155397	0	0
chrUn_gl000222	186861	0	0
chrUn_gl000223	180455	0	0
chrUn_gl000224	179693	0	0
chrUn_gl000225	211173	6	0
chrUn_gl000226	15008	0	0
chrUn_gl000227	128374	0	0
chrUn_gl000228	129120	0	0
chrUn_gl000229	19913	0	0
chrUn_gl000230	43691	0	0
chrUn_gl000231	27386	0	0
chrUn_gl000232	40652	0	0
chrUn_gl000233	45941	0	0
chrUn_gl000234	40531	0	0
chrUn_gl000235	34474	0	0
chrUn_gl000236	41934	0	0
chrUn_gl000237	45867	0	0
chrUn_gl000238	39939	0	0
chrUn_gl000239	33824	0	0
chrUn_gl000240	41933	0	0
chrUn_gl000241	42152	0	0
chrUn_gl000242	43523	0	0
chrUn_gl000243	43341	0	0
chrUn_gl000244	39929	0	0
chrUn_gl000245	36651	0	0
chrUn_gl000246	38154	0	0
chrUn_gl000247	36422	0	0
chrUn_gl000248	39786	0	0
chrUn_gl000249	38502	0	0
chrEBV	171823	0	0
*	0	0	0

Thank you!

**Comment by caleblareau** [comment]
Thanks for sharing! So the issue is that when you did your post processing with `grep` you removed the chrM from the bam header that then leads to this error. 

I would recommend running it just on "alignments.possorted.tagged.bam" since `bap` removes PCR duplicates itself. However, if you want run it on the .bam file that you currently specified, I would recommend using running with the `--mito-chromosome chrEBV` flag to get around the error. Since there are 0 reads, nothing will happen either way, as the chrM is mostly for collecting QC information.

**Comment by ShijingZHANG** [comment]
Thank you for your suggestion! I have run the `bap2 bam -i alignments.possorted.tagged.bam -o out -r hg19` and `bap2 bam -mc chrEBV -i alignment.last.bam -o out -r hg19,` however, I got the same error message.
"""
Traceback (most recent call last):
  File "/Users/zhangshijing/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/zhangshijing/anaconda3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/zhangshijing/Documents/scATAC-Seq/bap/bap/bin/python/20_names_split_filt.py", line 71, in writeBeadReadName
    Itr = bam.fetch(str(chrom),multiple_iterators=True)
  File "pysam/libcalignmentfile.pyx", line 1082, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 685, in pysam.libchtslib.HTSFile.parse_region
ValueError: invalid contig `chrM`
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/zhangshijing/Documents/scATAC-Seq/bap/bap/bin/python/20_names_split_filt.py", line 102, in <module>
    toy_out = pool.map(writeBeadReadName, zip(chrs, read_barcode_file))
  File "/Users/zhangshijing/anaconda3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/zhangshijing/anaconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ValueError: invalid contig `chrM`
Fri Mar 05 13:40:12 HKT 2021: Processing bam file using a Snakemake workflow. This is the most computationally intensive step.
Fri Mar 05 13:40:13 HKT 2021: ERROR: Snakemake execution failed. Check out/logs/alignments.possorted.tagged.snakemake.log file for more information. If blank, try allocating more memory.


 --mito-chromosome chrEBV

**Comment by ShijingZHANG** [comment]
I have tried using hg38 to do the BWA alignment, `samtools index debarcode.bam`, `bap-reanno -i debarcode.bam -o reanno_debarcode.bam` and then run bap2 bam -i reanno_debarcode.bam -o out -r hg38. And there are no `ValueError: invalid contig chrM` now. I think maybe this is because the chromosome mitochondria in hg19 is represented by "chrMT" instead of "chrM", so the bap2 can't identify it.

However, I got another error message about seqname this time. 

> Error in .subset2(x, i, exact = exact) : subscript out of bounds
Calls: [[ -> [[.data.frame -> <Anonymous>
Execution halted

I have converted the bam file, snakemake log information, and the idxstats result of bam file to txt. Thank you!
[reanno_debarcode_bam.txt](https://github.com/caleblareau/bap/files/6090077/reanno_debarcode_bam.txt)
[reanno_debarcode_snakemake_log.txt](https://github.com/caleblareau/bap/files/6090079/reanno_debarcode_snakemake_log.txt)
[reanno_debarcode_idxstats.txt](https://github.com/caleblareau/bap/files/6090081/reanno_debarcode_idxstats.txt)
