### ISSUE TITLE
Error in .subset2(x, i, exact = exact) : subscript out of bounds

### ISSUE THREAD

**Issue by ShijingZHANG** [caleblareau/bap#34]
Hello! Thank you for helping me solve the "chrM" error :)

However, I got another error message this time. My scATAC-seq data is prepared by Bio-Rad Surecell ATAC-Seq Library Prep Kit, so I also used bap-barcode to treat the raw fq.gz data. What I have run is:
1. `bap-barcode v2.1 -a test_seqtk_S1_L001_R1_1.fastq.gz -b test_seqtk_S1_L001_R2_1.fastq.gz --nmismatches 1`
2. `bwa mem /reference/hg38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna debarcode-c001_1.fastq.gz debarcode-c001_2.fastq.gz | samtools view -bS - |  samtools sort -@ 4 - -o debarcode.bam`
3. `bap-reanno -i debarcode.bam -o reanno_debarcode.bam`
4. `samtools index reanno_debarcode.bam `

After I got the reanno_debarcode.bam file, I then run `bap2 bam -i reanno_debarcode.bam -o out -r hg38`.

The error in snakemake.log is shown in following:

> Error in .subset2(x, i, exact = exact) : subscript out of bounds
> Calls: [[ -> [[.data.frame -> 
> Execution halted
> ESC[31mMissingOutputException in line 206 of 
> /Users/zhangshijing/Documents/scATAC-Seq/bap/bap/bin/snake/Snakefile.bap2.chr:
> Job Missing files after 5 seconds:
> out/temp/frag_overlap/reanno_debarcode.chr2_overlapCount.rds
> out/temp/frag_overlap/reanno_debarcode.chr2_ncCount.tsv
> This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait."

I have converted the bam file, snakemake log information, and the idxstats result of bam file to txt.

[reanno_debarcode_snakemake_log.txt](https://github.com/caleblareau/bap/files/6094645/reanno_debarcode_snakemake_log.txt)
[reanno_debarcode_idxstats.txt](https://github.com/caleblareau/bap/files/6094642/reanno_debarcode_idxstats.txt)
[reanno_debarcode_bam.txt](https://github.com/caleblareau/bap/files/6094643/reanno_debarcode_bam.txt)

Thank you!
Shijing

**Comment by ShijingZHANG** [comment]
Hello! I have fixed this bug by increasing the size of the input .bam file : )
Attached are the output figures in the "knee" dictionary.   I am wondering whether it is normal to get results like that?
![reanno_debarcode beadBarcodeKnee](https://user-images.githubusercontent.com/80019289/110209425-8501a000-7ec7-11eb-8c8e-4090a7b28c4c.png)
![reanno_debarcode jaccardOverlapKnee](https://user-images.githubusercontent.com/80019289/110209430-8af78100-7ec7-11eb-815e-010b72ff2b19.png)

Thank you very much!

Best wishes,
Shijing

**Comment by caleblareau** [comment]
Great!

The knees look pretty reasonable to me (i.e.e separating signal from noise), but it looks like the experiment was only shallowly sequenced?

**Comment by ShijingZHANG** [comment]
Maybe it is because I only used 1 pairs of fq.gz files after `bap-barcode` step?

In the `bap-barcode` step, the tool returned 21 pairs of fastq.gz files from one pair of raw fastq.gz files. The output of `bap-barcode` are labeled from "c001_1.fastq.gz c001_2.fastq.gz" to "c021_1.fastq.gz c021_2.fastq.gz". I only use the first pair  "c001_1.fastq.gz c001_2.fastq.gz" to do the `bap2 bam`, so that may cause the reads per barcode number to become low.
Do I need to merge those files from `bap-barcode` with `cat` before doing the `bap2 bam`?

Thank you!

**Comment by caleblareau** [comment]
Yes so in the default, bap-barcode emits a fastq (with the -c###) convention to enable aligning the reads in parallel and then merging them after read alignment. Then, one runs `bap2` on the fully merged bam. You could alternatively A) merge them all with cat as you suggested or b) increase the -nr flag in the bap-barcode execution.

**Comment by ShijingZHANG** [comment]
Thank you!
